#
# Cloud Foundation 
# Google Cloud Platform terragrunt pipeline
# 
# This workflow runs terragrunt code for several stages.
#
# Important: Ensure you have configured workload identity federation for github access
#
# Setup:
#   * Create and configure 'Workload identity federation' in your project.
#     Please feel free to use Cloud Foundation terraform-google-cf-projectcfg module
#     to create workload identity pool and provider for your GCP project in a convinient and simplified way
#     https://registry.terraform.io/modules/metro-digital/cf-projectcfg/google/latest
#     Check 'Inputs' table about service_accounts in a README.md file for details
#
# The workflow assumes you might have multiple environments with different service accounts.
# Each stage has a dedicated service account and gcp project number.
#
# Amount of stages and names can be adjusted by modifying the jobs strategy matrix. In current example it is only 1 stage - 'dev'
#
# Additionally the workflow will run terragrunt plan for any push or pull request on any branch, but only
# apply changes via terragrunt apply on commits pushed to the master branch.
# This can be adjusted by modifying the last step's conditions if needed.

name: 'GCP deployment'

on:
  push:

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is
    # ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.environment }}

    strategy:
      fail-fast: false
      matrix:
        environment: [dev]
        include:
          - environment: dev
            project_number: 123456789012 #your dev project number
            service_account: your_dev_service_account@domain.com #change to your dev project SA being used to run terraform code

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Install the latest version of Terraform CLI and configure the Terraform CLI
      # configuration file with a Terraform Cloud user API token
      # Ensure the terraform wrapper is disabled, see also:
      # https://github.com/gruntwork-io/terragrunt/issues/1202
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Setup terragrunt
        uses: metro-digital/cf-github-actions/terragrunt-setup@v1

      # In next step in case you're using CF terraform-google-cf-projectcfg module to configure workload identity federation change 123456789
      # to your actual project's number. As for the service account - change it accordingly to a service account you use to run terraform code
      # Note: if you use CF terraform-google-cf-projectcfg module and it's bootstrap script,
      # your SA will look like 'terraform-iac-pipeline@{gcp_project_id}.iam.gserviceaccount.com'
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/${{ matrix.project_number }}/locations/global/workloadIdentityPools/github-actions/providers/github'
          service_account: '${{ matrix.service_account }}'

      # Fail pipeline if code is not formatted proper
      - name: terragrunt hclfmt
        id: hclfmt
        run: terragrunt hclfmt --terragrunt-check

      # Checks that all configuration files are valid
      - name: terragrunt validate
        id: validate
        run: terragrunt run-all validate

      # Generates an execution plan for terragrunt
      - name: terragrunt plan
        id: plan
        run: terragrunt run-all plan -out=${{ github.sha }}.plan

      # On push to master, build or change infrastructure according to terragrunt configuration files
      - name: terragrunt apply
        id: apply
        if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        run: terragrunt run-all apply --terragrunt-non-interactive -auto-approve "${{ github.sha }}.plan"