name: Send notification via Email

on:
  workflow_run:
    workflows:
      - "WaaS: Deployment pipeline"
      - "WaaS: Deploy to production"
    types:
      - completed

jobs:
  send-notification:
    runs-on: [self-hosted, Linux, metro-network]
    steps:
      - name: Send notification email on workflow failure
        # Only send a notification if the workflow run failed
        # if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: wadeww/send-email-action@master
        with:
          server_address: ${{ secrets.MD_EMAIL_SERVER_NAME }}
          port: ${{ secrets.MD_EMAIL_SERVER_PORT }}
          subject: GitHub WaaS workflow run failed
          # Customize the message to your liking
          body: |
            WaaS workflow failed for ${{ github.repository }}:
            Commit message: ${{ github.event.workflow_run.head_commit.message }}
            Workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}
          to: <recipient01,recipient02>
          from: do-not-reply@metro.digital
