name: Send notifications via MS Teams

on:
  workflow_run:
    workflows:
      - "WaaS: Deployment pipeline"
      - "WaaS: Deploy to production"
    types:
      - completed

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification via Microsoft Teams
        # Only send a notification if the workflow run failed
        # if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: metro-digital/ms-teams-notification-action@v1.0.0
        with:
          # The webhook URL of the Microsoft Teams channel
          # You can create a webhook URL by following the instructions here: 
          # https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK_URL }}
