#
# SonarQube Static Code Analysis
# 
#
# Prerequisites:
# 1. Configure 'SONARQUBE_TOKEN' secret to be configured on the repository.
#    How to generate secret: https://docs.sonarqube.org/latest/user-guide/user-token/
# 
# 2. Set correct values for the following env variables: 
#       SOLUTION
#       VERTICAL
#       SERVICE
#
# Coverage reports:
#   To include coverage report on the SonarQube analysis, 
#     1. Uncomment the 'Generate coverprofile' step and generate there your coverage file(s).
#     2. Add parameter to the sonar-scanner in the 'SonarQube Scan' step.
#        The parameter name depends on the project language. 
#        More info: https://docs.sonarqube.org/latest/analysis/coverage/
#        Examples:
#           golang: -Dsonar.go.coverage.reportPaths=**/coverage.out
#           python: -Dsonar.python.coverage.reportPaths=path/to/coverage.xml
#           javascript: -Dsonar.javascript.lcov.reportPaths=./path/to/lcov.info
# 
# Sources Exclusion:
#   Source files to be excluded from the analysis can be listed in another parameter.
#   Paths are relative to the project base directory. The following wildcards can be used:
#       * - Match zero or more characters
#       ** - Match zero or more directories
#       ? - Match a single character
# 
#       More info: https://docs.sonarqube.org/latest/project-administration/narrowing-the-focus/
#       Example: -Dsonar.exclusions="**/*_test.go,**/mock.go"
#     
# 
# Other customizations: https://docs.sonarqube.org/latest/analysis/analysis-parameters/
#


name: sonarqube

on:
  push: 
    branches:
        - master
        
env:
  SOLUTION: "example-solution"
  VERTICAL: "example-vertical"
  SERVICE: "example-service"

jobs:
  scanner:
      name: SonarQube Trigger
      runs-on: self-hosted
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - uses: actions/setup-node@v3
        with:
            node-version: '16'

      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v4
        with:
          version: '4.8.0.2856'

    #   - name: Generate coverprofile
    #     run: |
    #         generate coverage report here

      - name: SonarQube Scan
        run: sonar-scanner
          -Dsonar.host.url="https://sonarqube.metrosystems.net"
          -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
          -Dsonar.projectKey=${{ env.SOLUTION }}.${{ env.VERTICAL }}.${{ env.SERVICE }}
        #   -Dsonar.exclusions="**/*_test.go,**/mock.go"
        #   -Dsonar.go.coverage.reportPaths=**/coverage.out